### ISSUE TITLE
Should support setting custom syntax through config

### ISSUE THREAD

**Issue by laander** [ascendancyy/vue-cli-plugin-stylelint#1]
All my styling is written in `scss` syntax and the `StyleLintPlugin` plugin for webpack needs the following setting to be able to understand the syntax:

```
new StyleLintPlugin({
  syntax: 'scss'
})
```

I don't currently see a way to inject this using your plugin or am i missing something? Otherwise a neat little plugin, thanks for the work!

**Comment by ascendancyy** [comment]
According to the api [docs](https://stylelint.io/user-guide/node-api/#syntax) the syntax should be inferred if not specified. Nonetheless I'll add this.
