### ISSUE TITLE
Update stylelint to 9.3.0

### ISSUE THREAD

**Issue by mario-d-s** [ascendancyy/vue-cli-plugin-stylelint#2]
This plugin depends on stylelint version 8.4.0. Can you please upgrade?
I'm encountering stylelint/stylelint#3183 which allegedly should be fixed in newer versions.

**Comment by steveworkman** [comment]
I've updated all the modules in this package in #6 - so merging that should resolve this one.

**Comment by lwyj123** [comment]
I got the `this[node.type] is not a function` error in `vue invoke @ascendancyy/vue-cli-plugin-stylelint`. Please merged this pr for fixed it. @ascendancyy

**Comment by lwyj123** [comment]
guys you can use this fork repo, https://github.com/sundogrd/vue-cli-plugin-stylelint.

```
npm install -D @lwyj123/vue-cli-plugin-stylelint
vue invoke @lwyj123/vue-cli-plugin-stylelint
```
