### ISSUE TITLE
SCSS syntax option makes stylelint try to lint JS?

### ISSUE THREAD

**Issue by irrg** [ascendancyy/vue-cli-plugin-stylelint#4]
This plugin looks exactly like what I need, but I can't figure out a way to pass the syntax option and, well, have things work.

```// vue.config.js
module.exports = {
  pluginOptions: {
    lintStyleOnBuild: false,
    stylelint: {
      syntax: 'scss'
    }
  }
}
```

This leads to stylelint trying to point out css errors in the JS code in my .vue files.

**Comment by ascendancyy** [comment]
I've been busy at uni and haven't had time to properly update the plugin to match changes in vue-cli which might the problem here. I'll hopefully take a look by next week.

**Comment by steveworkman** [comment]
I think this and issue #5 might be the same. Try the PR #6 and see if that helps

**Comment by ascendancyy** [comment]
It's been a while so I forgot exactly how stylelint works but omitting the syntax option and stylelint should be able to correctly infer the correct syntax. I think the `scss` value is meant for actual sass files and not combined files like `.vue` files.
