### ISSUE TITLE
Setting Stylelint config from a preset saves it as "[object Object]"

### ISSUE THREAD

**Issue by steveworkman** [ascendancyy/vue-cli-plugin-stylelint#5]
Using the Vue CLI (3.2.1) with this plugin and a preset, I want to configure stylelint using the preset.

From reading the code, the following preset should work

```json
{
  "useConfigFiles": false,
  "plugins": {
    "@vue/cli-plugin-babel": {},
    "@vue/cli-plugin-eslint": {
      "config": "prettier",
      "lintOn": ["save", "commit"]
    },
    "@vue/cli-plugin-unit-jest": {},
    "@ascendancyy/vue-cli-plugin-stylelint": {
      "lintStyleOn": ["build"],
      "config": {
        "extends": "stylelint-config-recommended-scss",
        "rules": {
          "comment-empty-line-before": "always",
          "max-empty-lines": 1,
          "selector-list-comma-newline-after": "always",
          "block-closing-brace-empty-line-before": "never",
          "block-opening-brace-space-before": "always",
          "block-opening-brace-newline-after": "always-multi-line"
        }
      }
    }
  },
  "router": false,
  "routerHistoryMode": false,
  "vuex": true,
  "cssPreprocessor": "sass",
  "configs": {
    "prettier": {
      "printWidth": 120
    }
  }
}
```

Two issues:

1. It's not listening to the "useConfigFiles" option
2. The .stylelintrc file that is produced does not contain the config that was passed in. Instead, it gives

```js
module.exports = {
  root: true,
  extends: ["[object Object]"]
};
```

If I write the config in the preset as a string, it then saves it as a string into the template, but that then won't be picked up.

**Comment by steveworkman** [comment]
I have a feeling the answer is in the template rendering, with an example of how to fix it here  https://stackoverflow.com/questions/13788314/express-and-ejs-to-render-a-json

**Comment by steveworkman** [comment]
PR available above

**Comment by ascendancyy** [comment]
I'm working on an update right now that should correctly address both your concerns. I had written this plugin during the cli beta and before the api for configs was added which is why I was using the template for the config file and why the useConfigFiles option is ignored.
